### PR TITLE
Added knowledge about savefile structure

### PR DESCRIPTION
**Pull request by ItsJ0el**

### CODE REVIEW

**Comment by EricFecteau** [comment]
Awesome, will merge when I get to a computer! Could you comment on if the table about the names/memory-locations is true for all the versions or if only NA 1.0 (or EU) was tested? The memory of the game changes significantly by version, so I was wondering if that was true for the save file too (other than end of file).

**Comment by ItsJ0el** [comment]
I tested it on EU, but NA should be similar, will update it

**Comment by EricFecteau** [comment]
Great EU 1.0 or 1.1? (you can check on the back of the cartridge 1.0 = ABCPN0JXX and 1.1 = ABCPN1JXX or here for a rom: https://github.com/EricFecteau/py_hmds/blob/master/documentation/versions/versions.md)

**Comment by ItsJ0el** [comment]
@EricFecteau 
I'm using files, so it's a bit hard to check the backside ;)
0x0000001E is empty on the JP file I used, so version is 1.0?

**Comment by EricFecteau** [comment]
Yes! 1.0 if 0x0000001E is 0!

**Review by EricFecteau — APPROVED** [review]

**Pull request merged**
